### ISSUE TITLE
Add New Page Error When Refresh the Page

### ISSUE THREAD

**Issue by swhp** [NanoDesuTranslations/editor#12]
When I want add new page, and refreshed the page I got error like this:

![snapshot1](https://cloud.githubusercontent.com/assets/7004831/18228344/aadec14a-7274-11e6-868c-0d0dcaaf923f.png)

**Comment by DerekRS** [comment]
Investigation notes:

When the page is refreshed, any information stored in memory is lost.  In this case, the stored information is the NavService's object about the series we're adding a page to.  We need that for hierarchy, series title, etc. in order to set initial properties of the page we're adding.

Getting that, as a normal user (with no access to the /series endpoint) means a new HTTP request (via PageService), borrowing logic from non-admin code of the Series page, plus structuring logic so the new page's props can be initialized after that page request has completed.

**Comment by swhp** [comment]
fix on release version [2.0.0](https://github.com/NanoDesuTranslations/editor/releases/tag/2.0.0)
